#**Pandas**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Data mining & ML/weather_data.csv")

In [7]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        7.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [8]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     32.833333   7.000000
std       4.020779   3.224903
min      28.000000   2.000000
25%      31.250000   6.250000
50%      32.000000   7.000000
75%      33.500000   7.750000
max      40.000000  12.000000

In [9]:
df.head(5)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        7.0  Sunny
2  1/5/2017         28.0        NaN   Snow
3  1/6/2017          NaN        7.0    NaN
4  1/7/2017         32.0        NaN   Rain

In [10]:
df.tail(5)

         day  temperature  windspeed   event
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [11]:
df.dtypes

day             object
temperature    float64
windspeed      float64
event           object
dtype: object

In [12]:
df.shape

(9, 4)

In [13]:
df.index

RangeIndex(start=0, stop=9, step=1)

In [14]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [15]:
df['event']

0      Rain
1     Sunny
2      Snow
3       NaN
4      Rain
5     Sunny
6       NaN
7    Cloudy
8     Sunny
Name: event, dtype: object

In [16]:
df['event'].value_counts()

Sunny     3
Rain      2
Snow      1
Cloudy    1
Name: event, dtype: int64

In [17]:
df.groupby('event').size()

event
Cloudy    1
Rain      2
Snow      1
Sunny     3
dtype: int64

In [18]:
df.groupby('event').get_group('Sunny')

         day  temperature  windspeed  event
1   1/4/2017          NaN        7.0  Sunny
5   1/8/2017         31.0        2.0  Sunny
8  1/11/2017         40.0       12.0  Sunny

In [19]:
df.isnull()

     day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False        False      False  False
6  False         True       True   True
7  False        False      False  False
8  False        False      False  False

In [20]:
df.isnull().sum()

day            0
temperature    3
windspeed      3
event          2
dtype: int64

In [21]:
df['temperature'].isnull()==True

0    False
1     True
2    False
3     True
4    False
5    False
6     True
7    False
8    False
Name: temperature, dtype: bool

In [22]:
new_df = df.fillna(0)
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        7.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [23]:

new_df = df.fillna({
        'temperature': 0,
        'windspeed': 0,
        'event': 'No Event'
    })
new_df

         day  temperature  windspeed     event
0   1/1/2017         32.0        6.0      Rain
1   1/4/2017          0.0        7.0     Sunny
2   1/5/2017         28.0        0.0      Snow
3   1/6/2017          0.0        7.0  No Event
4   1/7/2017         32.0        0.0      Rain
5   1/8/2017         31.0        2.0     Sunny
6   1/9/2017          0.0        0.0  No Event
7  1/10/2017         34.0        8.0    Cloudy
8  1/11/2017         40.0       12.0     Sunny

In [24]:
new_df = df.fillna(method="ffill")
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        7.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [25]:
new_df = df.fillna(method="bfill")
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        7.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        2.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017         34.0        8.0  Cloudy
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [26]:
new_df = df.dropna()
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
5   1/8/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny